### ISSUE TITLE
Logistic Regression Bug fix

### ISSUE THREAD

**Issue by Coldestadam** [BreakoutMentors/Data-Science-and-Machine-Learning#27]
## Why
There was a bug in the confusion matrix explanation part of the lesson

### Breakdown
Explain your approach to implementing the change. Include the changes you will be making in each repository.
- [x] Data-Science-and-Machine-Learning
  - [x] Fixed bug

### QA Plan
Have Kai review it.
- [x] ∞

### Post Release
Explain the lesson to the kids.
- [x] ∞

**Comment by krmiddlebrook** [comment]
Log. Reg. bugs resolved!
