### ISSUE TITLE
Medical Diagnosis CNN + Image Processing Demo Notebook 

### ISSUE THREAD

**Issue by krmiddlebrook** [BreakoutMentors/Data-Science-and-Machine-Learning#5]
## Why
We want to provide students with a medical domain example they can use to learn how to use CNNs to solve medical image diagnosis / recognition problems. 

### Breakdown
Explain your approach to implementing the change. Include the changes you will be making in each repository.
- [x] Data-Science-and-Machine-Learning
  - [x] Select a common medical image diagnosis dataset.
  - [x] Provide a short description about what medical image diagnosis is and how ML can be used to improve diagnosis results. 
  - [x] Briefly outline image preprocessing
  - [x] Introduce CNNs (high-level is ok, don't need to cover maths of it. The shorter the better as long as it doesn't sacrifice core concepts)
  - [x] Build CNN model and use it to solve the problem.
  - [x] Introduce data augmentation methods for image data.
  - [x] Combine CNN model & data augmentation method and retrain model again, should produce better results.
  - [x] Conclusion / Summary and next steps (i.e., suggest another dataset that the students could use).

### QA Plan
Steps you will follow locally and on the cloud to verify expected behavior of all affected areas.
- [ ] Have @krmiddlebrook review content before merging into main.

### Post Release
Non destructive QA we can perform post release to verify things are working.
- [ ] Use this notebook to teach students.

**Comment by Coldestadam** [comment]
All ready to review!
